[avito]
tg_token = ""
tg_chat_id = [
    ""
]
urls = [
    "https://www.avito.ru/izhevsk/tovary_dlya_kompyutera/dzhoystiki_i_ruli-ASgBAgICAUTGB7ZO?cd=1&localPriority=0&q=moza+r5&s=104",
]
count = 1
keys_word_white_list = []
keys_word_black_list = []
seller_black_list = []
max_price = 9999999999
min_price = 1000
geo = ""
proxy_string = ""
proxy_change_url = ""
pause_general = 7
pause_between_links = 1
max_age = 600
max_count_of_retry = 5
ignore_reserv = false
ignore_promotion = false
one_time_start = false
one_file_for_link = false
parse_views = false
save_xlsx = true
use_webdriver = true
